development:
  adapter: mysql2
  encoding: utf8
  database: desafio
  username: root
  password: tttzzz

test:
  adapter: mysql2
  encoding: utf8
  database: desafio_test
  username: root
  password: tttzzz